'use client'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createContext, useContext, useEffect, useEffectEvent, useMemo, useRef, useState } from 'react'
import { ArrowLeft, Cast, Check, ChevronLeft, ChevronRight, Clapperboard, ExternalLink, Eye, EyeOff, Focus, Lock, LockOpen, MapPin, Maximize, MonitorPlay, Plus, Radio, Search, Square, Tag, X } from 'lucide-react'
import { HTMLContainer, Rectangle2d, ShapeUtil, T, Tldraw, createShapeId, getSnapshot, type Editor, type TLBaseShape, type TLEditorSnapshot, type TLEventMapHandler, type TLResizeInfo, type TLUiOverrides } from 'tldraw'
import 'tldraw/tldraw.css'
import type { Scene, SceneGrid } from '@/domain/scenes/scene'
import type { ProjectionCamera, ProjectionSpotlight, ProjectionState } from '@/domain/projection/projection'
import type { SceneEntitySummary, SceneNavigationSummary, ScenePoiSummary } from './scene-types'
import { EntityTypeIcon } from '@/components/entities/entity-type-icon'
import { PageScrollLock } from '@/components/entities/page-scroll-lock'
import { assetVariantUrl } from '@/lib/assetUrl'
import { BroadcastChannelProjectionTransport } from '@/lib/projection/broadcast-channel-transport'
import { buildProjectionState, type ProjectionRuntimePoi, type ProjectionRuntimeToken } from '@/lib/projection/projection-state-builder'
import { ProjectionDisplay } from './projection-display'
import { ScenePicker } from './scene-picker'
import styles from './scene-runner.module.css'

const BG = 'scene-background', TOKEN = 'scene-token', POI = 'scene-poi'
const TOKEN_SCALE_STEP = 1.1, TOKEN_MIN_WIDTH = 48, TOKEN_MIN_HEIGHT = 72, TOKEN_MAX_SIZE = 2400
const OPEN_TOKEN_EVENT = 'canon-codex:open-scene-token', OPEN_POI_EVENT = 'canon-codex:open-scene-poi'
const stripNativeShortcuts = <T extends Record<string, { kbd?: string }>>(items: T): T => Object.fromEntries(Object.entries(items).map(([id, item]) => [id, { ...item, kbd: undefined }])) as T
const sceneUiOverrides: TLUiOverrides = {
 actions(_editor, actions) { return stripNativeShortcuts(actions) },
 tools(_editor, tools) { return stripNativeShortcuts(tools) },
}
declare module 'tldraw' { interface TLGlobalShapePropsMap {
  [BG]: { w: number; h: number; assetId: string }
  [TOKEN]: { w: number; h: number; entityId: string; representation: string; visibility: string; locked: boolean }
  [POI]: { w: number; h: number; poiId: string; visibility: string }
} }
type BgShape = TLBaseShape<typeof BG, { w:number; h:number; assetId:string }>
type TokenShape = TLBaseShape<typeof TOKEN, { w:number; h:number; entityId:string; representation:string; visibility:string; locked:boolean }>
type PoiShape = TLBaseShape<typeof POI, { w:number; h:number; poiId:string; visibility:string }>
const EntityCtx = createContext(new Map<string, SceneEntitySummary>()), PoiCtx = createContext(new Map<string, ScenePoiSummary>()), ModeCtx = createContext<'edit'|'run'|'presentation'>('edit'), PresentationPoisCtx = createContext(true), GridCtx = createContext<SceneGrid>({ enabled:false,type:'square',cellSize:70,offsetX:0,offsetY:0,opacity:.25,snapTokens:false })

function BackgroundContent({s}:{s:BgShape}){const grid=useContext(GridCtx);return <HTMLContainer className={styles.background} style={{width:s.props.w,height:s.props.h}}><Image src={assetVariantUrl(s.props.assetId,'original')} alt="" width={s.props.w} height={s.props.h} unoptimized draggable={false}/>{grid.enabled&&<div className={styles.grid} style={{opacity:grid.opacity,backgroundSize:`${grid.cellSize}px ${grid.cellSize}px`,backgroundPosition:`${grid.offsetX}px ${grid.offsetY}px`}}/>}</HTMLContainer>}
class BackgroundUtil extends ShapeUtil<BgShape> { static override type=BG; static override props={w:T.number,h:T.number,assetId:T.string}; getDefaultProps(){return {w:1200,h:800,assetId:''}}; getGeometry(s:BgShape){return new Rectangle2d({width:s.props.w,height:s.props.h,isFilled:true})}; component(s:BgShape){return <BackgroundContent s={s}/>}; getIndicatorPath(){return undefined}; override canResize(){return false}; override canEdit(){return false} }
function TokenContent({s}:{s:TokenShape}){const e=useContext(EntityCtx).get(s.props.entityId),mode=useContext(ModeCtx),hidden=s.props.visibility==='hidden',flipped=Boolean((s.meta as {flipX?:boolean}).flipX);if(hidden&&mode==='presentation')return null;return <div className={`${styles.token} ${s.props.representation==='round'?styles.round:styles.cutout} ${hidden?styles.hidden:''} ${flipped?styles.flipped:''}`}>{e?.assetId?<Image src={assetVariantUrl(e.assetId,'original')} alt="" width={500} height={700} unoptimized draggable={false}/>:<div className={styles.missing}>{e?<EntityTypeIcon name={e.typeIcon}/>:<span>?</span>}</div>}{mode!=='presentation'&&<span className={styles.tokenName}>{e?.title??'Entidade ausente'}</span>}{hidden&&mode!=='presentation'&&<EyeOff className={styles.hiddenIcon}/>}</div>}
class TokenUtil extends ShapeUtil<TokenShape>{static override type=TOKEN;static override props={w:T.number,h:T.number,entityId:T.string,representation:T.string,visibility:T.string,locked:T.boolean};getDefaultProps(){return {w:180,h:280,entityId:'',representation:'cutout',visibility:'visible',locked:false}};getGeometry(s:TokenShape){return new Rectangle2d({width:s.props.w,height:s.props.h,isFilled:true})};component(s:TokenShape){return <HTMLContainer className={styles.shape} style={{width:s.props.w,height:s.props.h}}><TokenContent s={s}/></HTMLContainer>};getIndicatorPath(s:TokenShape){const p=new Path2D();p.rect(0,0,s.props.w,s.props.h);return p};override canResize(s:TokenShape){return !s.props.locked};override isAspectRatioLocked(){return true};override onResize(s:TokenShape,i:TLResizeInfo<TokenShape>){const w=Math.max(48,s.props.w*i.scaleX),h=s.props.representation==='round'?w:Math.max(72,s.props.h*i.scaleY);return{props:{w,h}}};override onDoubleClick(s:TokenShape){return{id:s.id,type:TOKEN as typeof TOKEN,props:{}}}}
function PoiContent({s}:{s:PoiShape}){const p=useContext(PoiCtx).get(s.props.poiId),mode=useContext(ModeCtx),presentationPoisVisible=useContext(PresentationPoisCtx),hidden=s.props.visibility==='hidden';if(mode==='presentation'&&(hidden||!presentationPoisVisible))return null;return <div className={`${styles.poi} ${hidden?styles.hidden:''}`}><i/><span>{p?.label??'Ponto indisponível'}</span>{hidden&&mode!=='presentation'&&<EyeOff/>}</div>}
class PoiUtil extends ShapeUtil<PoiShape>{static override type=POI;static override props={w:T.number,h:T.number,poiId:T.string,visibility:T.string};getDefaultProps(){return{w:180,h:38,poiId:'',visibility:'visible'}};getGeometry(s:PoiShape){return new Rectangle2d({width:s.props.w,height:s.props.h,isFilled:true})};component(s:PoiShape){return <HTMLContainer className={styles.shape} style={{width:s.props.w,height:s.props.h}}><PoiContent s={s}/></HTMLContainer>};getIndicatorPath(s:PoiShape){const p=new Path2D();p.rect(0,0,s.props.w,s.props.h);return p};override canResize(){return false};override onDoubleClick(s:PoiShape){return{id:s.id,type:POI as typeof POI,props:{}}}}
const shapeUtils=[BackgroundUtil,TokenUtil,PoiUtil]

function SceneQuickPanel({entity,poi,onClose,onNavigate,revealable=false,revealedDiscoveryIds=[],onToggleDiscovery}:{entity?:SceneEntitySummary;poi?:ScenePoiSummary;onClose:()=>void;onNavigate:(href:string)=>void;revealable?:boolean;revealedDiscoveryIds?:string[];onToggleDiscovery?:(id:string)=>void}){
 return <aside className={styles.presentationPreview}><div className={styles.previewHeader}><span>{entity?'Ficha rápida':'Ponto de interesse'}</span><button onClick={onClose}><X/></button></div>{entity&&<><div className={styles.previewPhoto}>{entity.assetId?<Image src={assetVariantUrl(entity.assetId,'original')} alt="" width={640} height={480} unoptimized/>:<EntityTypeIcon name={entity.typeIcon}/>}</div><div className={styles.previewIntro}><p>{entity.typeLabel}</p><h2>{entity.title}</h2>{entity.subtitle&&<span>{entity.subtitle}</span>}{entity.status&&<em>{entity.status}</em>}</div>{entity.aliases.length>0&&<div className={styles.previewAliases}><small>Também conhecido como</small><p>{entity.aliases.join(' · ')}</p></div>}{entity.fields.length>0&&<dl className={styles.previewFields}>{entity.fields.map((field)=><div key={field.label} className={field.wide?styles.previewFieldWide:undefined}><dt>{field.label}</dt><dd>{field.value}</dd></div>)}</dl>}<div className={styles.previewTags}>{entity.tags.map((tag)=><span key={tag}><Tag/>{tag}</span>)}</div><button className={styles.previewLink} onClick={()=>onNavigate(`/entity/${entity.id}`)}>Abrir página completa <ExternalLink/></button></>}{poi&&<><div className={styles.poiPreviewTitle}><MapPin/><div><small>{poi.kind==='text'?'Local de interesse':poi.kind==='evidence'?'Evidência':'Documento'}</small><h2>{poi.label}</h2></div></div>{poi.description&&<p className={styles.poiDescription}>{poi.description}</p>}{poi.discoveries.length>0&&<div className={styles.discoveries}>{poi.discoveries.map((discovery)=>{const revealed=revealedDiscoveryIds.includes(discovery.id);return <article key={discovery.id} data-revealed={revealed}><header><strong>{discovery.approach||'Abordagem livre'}</strong>{discovery.condition&&<span>{discovery.condition}</span>}{revealable&&<button className={styles.discoveryReveal} onClick={()=>onToggleDiscovery?.(discovery.id)}>{revealed?<EyeOff/>:<Eye/>}{revealed?'Ocultar':'Revelar'}</button>}</header><p>{discovery.information}</p></article>})}</div>}{poi.linkedEntityId&&<button className={styles.previewLink} onClick={()=>onNavigate(`/entity/${poi.linkedEntityId}`)}>Abrir item relacionado <ExternalLink/></button>}</>}</aside>
}

export function SceneRunner({scene,scenes,entities,pois,locationTitle,initialMode}:{scene:Scene;scenes:SceneNavigationSummary[];entities:SceneEntitySummary[];pois:ScenePoiSummary[];locationTitle:string;initialMode:'edit'|'run'|'presentation'}){
 const router=useRouter();const editorRef=useRef<Editor|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),gridRef=useRef(scene.grid),projectionTransportRef=useRef<BroadcastChannelProjectionTransport|null>(null),projectionUnsubscribeRef=useRef<(()=>void)|null>(null),projectionWindowRef=useRef<Window|null>(null),projectionSessionRef=useRef<string|null>(null),projectionStateRef=useRef<ProjectionState|null>(null),projectionSpotlightRef=useRef<ProjectionSpotlight|null>(null),revealedPoiInfoRef=useRef<Record<string,string[]>>({}),projectionFrameRef=useRef<number|null>(null),projectionRevisionRef=useRef(0),projectionActiveRef=useRef(false),playerPreviewRef=useRef(false),followCameraRef=useRef(true),lastProjectionPingRef=useRef(0);const [mode,setMode]=useState<'edit'|'run'|'presentation'>(initialMode),[grid,setGrid]=useState(scene.grid),[query,setQuery]=useState(''),[selected,setSelected]=useState<TokenShape|null>(null),[tokens,setTokens]=useState<TokenShape[]>([]),[saved,setSaved]=useState(true),[poiStates,setPoiStates]=useState<Record<string,string>>({}),[presentationPoisVisible,setPresentationPoisVisible]=useState(true),[preview,setPreview]=useState<{kind:'entity'|'poi';id:string}|null>(null),[revealedPoiInfo,setRevealedPoiInfo]=useState<Record<string,string[]>>({}),[runPanelOpen,setRunPanelOpen]=useState(true),[projectionActive,setProjectionActive]=useState(false),[projectionConnected,setProjectionConnected]=useState(false),[followCamera,setFollowCamera]=useState(true),[playerPreview,setPlayerPreview]=useState(false),[playerState,setPlayerState]=useState<ProjectionState|null>(null),[pickerOpen,setPickerOpen]=useState(false)
 const entityMap=useMemo(()=>new Map(entities.map(e=>[e.id,e])),[entities]),poiMap=useMemo(()=>new Map(pois.map(p=>[p.id,p])),[pois]);const filtered=entities.filter(e=>`${e.title} ${e.typeLabel}`.toLowerCase().includes(query.toLowerCase()))
 const makeProjectionState=(editor:Editor,revision=projectionRevisionRef.current)=>{const ordered=editor.getCurrentPageShapesSorted(),bounds=editor.getViewportPageBounds(),camera=editor.getCamera(),publicTokens:ProjectionRuntimeToken[]=ordered.flatMap((shape,index)=>{if(shape.type!==TOKEN)return[];const token=shape as TokenShape,entity=entityMap.get(token.props.entityId);return[{id:token.id,x:token.x,y:token.y,width:token.props.w,height:token.props.h,rotation:token.rotation,zIndex:index,representation:token.props.representation==='round'?'round':'cutout',assetId:entity?.assetId,flipX:Boolean((token.meta as {flipX?:boolean}).flipX),visibility:token.props.visibility==='visible'?'visible':'hidden'}]}),publicPois:ProjectionRuntimePoi[]=ordered.flatMap((shape,index)=>{if(shape.type!==POI)return[];const marker=shape as PoiShape,poi=poiMap.get(marker.props.poiId);if(!poi)return[];return[{id:marker.id,x:marker.x,y:marker.y,width:marker.props.w,height:marker.props.h,rotation:marker.rotation,zIndex:index,title:poi.label,publicDescription:poi.description,visibility:marker.props.visibility==='visible'?'visible':'hidden'}]});const projectionCamera:ProjectionCamera={centerX:bounds.center.x,centerY:bounds.center.y,zoom:camera.z,viewWidth:bounds.w,viewHeight:bounds.h,sceneWidth:scene.background.width,sceneHeight:scene.background.height};return buildProjectionState({sceneId:scene.id,title:scene.title,background:{assetId:scene.background.assetId,width:scene.background.width,height:scene.background.height},tokens:publicTokens,pointsOfInterest:publicPois,grid:{enabled:gridRef.current.enabled,cellSize:gridRef.current.cellSize,offsetX:gridRef.current.offsetX,offsetY:gridRef.current.offsetY,opacity:gridRef.current.opacity},camera:projectionCamera,spotlight:projectionSpotlightRef.current},revision)}
 const sendFullProjectionState=()=>{const editor=editorRef.current,transport=projectionTransportRef.current;if(!editor)return;const revision=++projectionRevisionRef.current,state=makeProjectionState(editor,revision);projectionStateRef.current=state;if(playerPreviewRef.current)setPlayerState(state);transport?.publish({type:'FULL_STATE',state})}
 const syncProjection=()=>{projectionFrameRef.current=null;const editor=editorRef.current;if(!editor||(!projectionActiveRef.current&&!playerPreviewRef.current))return;const previous=projectionStateRef.current;if(!previous){sendFullProjectionState();return}const candidate=makeProjectionState(editor,previous.revision);if(!followCameraRef.current)candidate.camera=previous.camera;const transport=projectionTransportRef.current,same=(left:unknown,right:unknown)=>JSON.stringify(left)===JSON.stringify(right);if(!same(previous.background,candidate.background)||!same(previous.grid,candidate.grid)||previous.sceneId!==candidate.sceneId){sendFullProjectionState();return}let revision=previous.revision;const publish=(message:Parameters<BroadcastChannelProjectionTransport['publish']>[0])=>transport?.publish(message);const previousTokens=new Map(previous.tokens.map((token)=>[token.id,token])),nextTokens=new Map(candidate.tokens.map((token)=>[token.id,token]));for(const [id] of previousTokens)if(!nextTokens.has(id))publish({type:'TOKEN_REMOVE',revision:++revision,tokenId:id});for(const token of candidate.tokens)if(!same(previousTokens.get(token.id),token))publish({type:'TOKEN_UPDATE',revision:++revision,token});const previousPois=new Map(previous.pointsOfInterest.map((poi)=>[poi.id,poi])),nextPois=new Map(candidate.pointsOfInterest.map((poi)=>[poi.id,poi]));for(const [id] of previousPois)if(!nextPois.has(id))publish({type:'POI_REMOVE',revision:++revision,poiId:id});for(const poi of candidate.pointsOfInterest)if(!same(previousPois.get(poi.id),poi))publish({type:'POI_UPDATE',revision:++revision,poi});if(followCameraRef.current&&!same(previous.camera,candidate.camera))publish({type:'CAMERA_UPDATE',revision:++revision,camera:candidate.camera});if(!same(previous.spotlight,candidate.spotlight))publish({type:'SPOTLIGHT_UPDATE',revision:++revision,spotlight:candidate.spotlight});projectionRevisionRef.current=revision;candidate.revision=revision;projectionStateRef.current=candidate;if(playerPreviewRef.current)setPlayerState(candidate)}
 const scheduleProjectionSync=()=>{if(projectionFrameRef.current===null)projectionFrameRef.current=requestAnimationFrame(syncProjection)}
 const stopProjection=()=>{projectionTransportRef.current?.publish({type:'PROJECTION_STOPPED'});projectionUnsubscribeRef.current?.();projectionTransportRef.current?.disconnect();projectionTransportRef.current=null;projectionUnsubscribeRef.current=null;projectionActiveRef.current=false;projectionStateRef.current=null;setProjectionActive(false);setProjectionConnected(false)}
 const startProjection=()=>{if(projectionActiveRef.current){if(projectionSessionRef.current)projectionWindowRef.current=window.open(`/projection/${projectionSessionRef.current}`,'canon-codex-projection','popup=yes,width=1280,height=720');projectionWindowRef.current?.focus();return}const sessionId=`projection-${crypto.randomUUID()}`,transport=new BroadcastChannelProjectionTransport();projectionSessionRef.current=sessionId;projectionTransportRef.current=transport;projectionActiveRef.current=true;projectionRevisionRef.current=0;projectionStateRef.current=null;setProjectionActive(true);setProjectionConnected(false);transport.connect(sessionId);projectionUnsubscribeRef.current=transport.subscribe((message)=>{if(message.type==='PROJECTION_READY'||message.type==='REQUEST_FULL_STATE'){lastProjectionPingRef.current=Date.now();setProjectionConnected(true);sendFullProjectionState()}else if(message.type==='PING'){lastProjectionPingRef.current=Date.now();setProjectionConnected(true);transport.publish({type:'PONG'})}});projectionWindowRef.current=window.open(`/projection/${sessionId}`,'canon-codex-projection','popup=yes,width=1280,height=720');scheduleProjectionSync()}
 const togglePlayerPreview=()=>{const next=!playerPreviewRef.current;playerPreviewRef.current=next;setPlayerPreview(next);if(next){projectionStateRef.current=null;scheduleProjectionSync()}else setPlayerState(null)}
 const persistScene=async(editor:Editor,nextGrid:SceneGrid)=>{setSaved(false);try{const{document}=getSnapshot(editor.store);const r=await fetch(`/api/scenes/${scene.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({snapshot:{document},grid:nextGrid})});setSaved(r.ok);return r.ok}catch{return false}}
 const scheduleSave=(editor:Editor,nextGrid=gridRef.current)=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{timer.current=null;void persistScene(editor,nextGrid)},650)}
 const goToScene=async(id:string)=>{setPickerOpen(false);if(id===scene.id)return;const editor=editorRef.current;if(timer.current&&editor){clearTimeout(timer.current);timer.current=null;if(!await persistScene(editor,gridRef.current))return}router.push(`/scenes/${id}${mode==='edit'?'':`?mode=${mode}`}`)}
 const syncSelection=(editor:Editor)=>{const s=editor.getSelectedShapes().find((x):x is TokenShape=>x.type===TOKEN);setSelected(s??null)}
 const syncTokens=(editor:Editor)=>setTokens(editor.getCurrentPageShapes().filter((s):s is TokenShape=>s.type===TOKEN))
 const onMount=(editor:Editor)=>{editorRef.current=editor;const b=scene.background;editor.setCameraOptions({constraints:{bounds:{x:0,y:0,w:b.width,h:b.height},padding:{x:40,y:40},origin:{x:.5,y:.5},initialZoom:'fit-max',baseZoom:'fit-max',behavior:'contain'}})
  if(!editor.getCurrentPageShapes().some(s=>s.type===BG)){const id=createShapeId();editor.createShape<BgShape>({id,type:BG,x:0,y:0,props:{w:b.width,h:b.height,assetId:b.assetId},isLocked:true});editor.sendToBack([id])}
  for(const p of pois){const existing=editor.getCurrentPageShapes().find((s):s is PoiShape=>s.type===POI&&s.props.poiId===p.id);const x=b.width*p.x/100-18,y=b.height*p.y/100-18;if(existing)editor.updateShape<PoiShape>({id:existing.id,type:POI,x,y,isLocked:true});else editor.createShape<PoiShape>({type:POI,x,y,props:{poiId:p.id},isLocked:true})}
  setPoiStates(Object.fromEntries(editor.getCurrentPageShapes().filter((s):s is PoiShape=>s.type===POI).map((s)=>[s.props.poiId,s.props.visibility])))
  syncTokens(editor)
  editor.zoomToBounds({x:0,y:0,w:b.width,h:b.height},{inset:40,animation:{duration:250}})
  const stopDoc=editor.store.listen(()=>{scheduleSave(editor);scheduleProjectionSync()},{source:'user',scope:'document'}),stopSession=editor.store.listen(()=>{syncSelection(editor);scheduleProjectionSync()},{source:'all',scope:'session'});const handleEvent:TLEventMapHandler<'event'>=(event)=>{if(event.name==='double_click'&&event.phase==='down'){const hit=[...editor.getShapesAtPoint(editor.inputs.getCurrentPagePoint(),{hitInside:true,margin:editor.getHitTestMargin()})].reverse().find((shape)=>shape.type===TOKEN||shape.type===POI);if(hit?.type===TOKEN)window.dispatchEvent(new CustomEvent(OPEN_TOKEN_EVENT,{detail:(hit as TokenShape).props.entityId}));if(hit?.type===POI)window.dispatchEvent(new CustomEvent(OPEN_POI_EVENT,{detail:(hit as PoiShape).props.poiId}));return}if(event.name!=='pointer_up')return;const clicked=[...editor.getShapesAtPoint(editor.inputs.getCurrentPagePoint(),{hitInside:true,margin:editor.getHitTestMargin()})].reverse().find((shape)=>shape.type===POI);if(clicked?.type===POI)window.dispatchEvent(new CustomEvent(OPEN_POI_EVENT,{detail:(clicked as PoiShape).props.poiId}));const activeGrid=gridRef.current;if(activeGrid.snapTokens){for(const s of editor.getSelectedShapes()){if(s.type!==TOKEN||(s as TokenShape).props.representation!=='round')continue;editor.updateShape({id:s.id,type:TOKEN,x:Math.round((s.x-activeGrid.offsetX)/activeGrid.cellSize)*activeGrid.cellSize+activeGrid.offsetX,y:Math.round((s.y-activeGrid.offsetY)/activeGrid.cellSize)*activeGrid.cellSize+activeGrid.offsetY})}}syncTokens(editor)};editor.on('event',handleEvent);scheduleProjectionSync();return()=>{stopDoc();stopSession();editor.off('event',handleEvent)}}
 const openScenePreview=(kind:'entity'|'poi',id:string)=>{setPreview({kind,id});if(kind==='entity'){const entity=entityMap.get(id);projectionSpotlightRef.current=entity?{kind:'entity',id:entity.id,title:entity.title,typeLabel:entity.typeLabel,assetId:entity.assetId,subtitle:entity.subtitle,status:entity.status,aliases:entity.aliases,tags:entity.tags,fields:entity.fields}:null}else{const poi=poiMap.get(id),revealed=revealedPoiInfoRef.current[id]??[],marker=editorRef.current?.getCurrentPageShapes().find((shape):shape is PoiShape=>shape.type===POI&&shape.props.poiId===id);projectionSpotlightRef.current=poi&&marker?.props.visibility==='visible'?{kind:'poi',id:poi.id,title:poi.label,poiKind:poi.kind,publicDescription:poi.description,discoveries:poi.discoveries.filter((item)=>revealed.includes(item.id))}:null}scheduleProjectionSync()}
 const closeScenePreview=()=>{setPreview(null);projectionSpotlightRef.current=null;scheduleProjectionSync()}
 const togglePoiDiscovery=(poiId:string,discoveryId:string)=>{const current=revealedPoiInfoRef.current[poiId]??[],next=current.includes(discoveryId)?current.filter((id)=>id!==discoveryId):[...current,discoveryId],all={...revealedPoiInfoRef.current,[poiId]:next};revealedPoiInfoRef.current=all;setRevealedPoiInfo(all);if(preview?.kind==='poi'&&preview.id===poiId){const poi=poiMap.get(poiId),marker=editorRef.current?.getCurrentPageShapes().find((shape):shape is PoiShape=>shape.type===POI&&shape.props.poiId===poiId);projectionSpotlightRef.current=poi&&marker?.props.visibility==='visible'?{kind:'poi',id:poi.id,title:poi.label,poiKind:poi.kind,publicDescription:poi.description,discoveries:poi.discoveries.filter((item)=>next.includes(item.id))}:null;scheduleProjectionSync()}}
 const handlePreviewEvent=useEffectEvent((kind:'entity'|'poi',id:string)=>{if(mode==='run'||mode==='presentation')openScenePreview(kind,id)})
 useEffect(()=>{router.refresh()},[router]);useEffect(()=>{const health=window.setInterval(()=>{if(projectionActiveRef.current&&lastProjectionPingRef.current&&Date.now()-lastProjectionPingRef.current>5000)setProjectionConnected(false)},2000);return()=>{window.clearInterval(health);if(timer.current)clearTimeout(timer.current);if(projectionFrameRef.current!==null)cancelAnimationFrame(projectionFrameRef.current);stopProjection()}},[])
 useEffect(()=>{const openToken=(event:Event)=>handlePreviewEvent('entity',(event as CustomEvent<string>).detail);const openPoi=(event:Event)=>handlePreviewEvent('poi',(event as CustomEvent<string>).detail);window.addEventListener(OPEN_TOKEN_EVENT,openToken);window.addEventListener(OPEN_POI_EVENT,openPoi);return()=>{window.removeEventListener(OPEN_TOKEN_EVENT,openToken);window.removeEventListener(OPEN_POI_EVENT,openPoi)}},[])
 const addToken=(id:string)=>{const e=editorRef.current;if(!e)return;const c=e.getViewportPageBounds().center;e.createShape<TokenShape>({type:TOKEN,x:c.x-90,y:c.y-140,props:{entityId:id}});e.setCurrentTool('select');syncTokens(e)}
 const update=(props:Partial<TokenShape['props']>)=>{const e=editorRef.current;if(!e||!selected)return;e.updateShape<TokenShape>({id:selected.id,type:TOKEN,props});syncSelection(e);syncTokens(e)}
 const flipSelectedToken=()=>{const editor=editorRef.current;if(!editor||!selected||mode==='presentation')return;editor.updateShape<TokenShape>({id:selected.id,type:TOKEN,meta:{...selected.meta,flipX:!Boolean((selected.meta as {flipX?:boolean}).flipX)}});syncSelection(editor);syncTokens(editor);scheduleProjectionSync()}
 const scaleSelectedToken=(factor:number)=>{const editor=editorRef.current;if(!editor||!selected||selected.props.locked||mode==='presentation')return;const minHeight=selected.props.representation==='round'?TOKEN_MIN_WIDTH:TOKEN_MIN_HEIGHT,minFactor=Math.max(TOKEN_MIN_WIDTH/selected.props.w,minHeight/selected.props.h),maxFactor=Math.min(TOKEN_MAX_SIZE/selected.props.w,TOKEN_MAX_SIZE/selected.props.h),appliedFactor=Math.min(maxFactor,Math.max(minFactor,factor));if(Math.abs(appliedFactor-1)<.001)return;const width=Math.round(selected.props.w*appliedFactor*10)/10,height=selected.props.representation==='round'?width:Math.round(selected.props.h*appliedFactor*10)/10;editor.updateShape<TokenShape>({id:selected.id,type:TOKEN,x:selected.x-(width-selected.props.w)/2,y:selected.y-(height-selected.props.h)/2,props:{w:width,h:height}});syncSelection(editor);syncTokens(editor);scheduleProjectionSync()}
 const toggleToken=(token:TokenShape)=>{const e=editorRef.current;if(!e)return;e.updateShape<TokenShape>({id:token.id,type:TOKEN,props:{visibility:token.props.visibility==='visible'?'hidden':'visible'}});syncTokens(e);syncSelection(e)}
 const changeGrid=(patch:Partial<SceneGrid>)=>{const next={...gridRef.current,...patch};gridRef.current=next;setGrid(next);if(editorRef.current){scheduleSave(editorRef.current,next);scheduleProjectionSync()}}
 const allPois=(visibility:string)=>{const e=editorRef.current;if(!e)return;const shapes=e.getCurrentPageShapes().filter((s):s is PoiShape=>s.type===POI);e.updateShapes(shapes.map((s)=>({id:s.id,type:POI,isLocked:false})));e.updateShapes(shapes.map((s)=>({id:s.id,type:POI,isLocked:true,props:{visibility}})));setPoiStates(Object.fromEntries(pois.map((p)=>[p.id,visibility])));if(preview?.kind==='poi'){if(visibility==='visible')openScenePreview('poi',preview.id);else projectionSpotlightRef.current=null}scheduleProjectionSync()}
 const togglePoi=(poiId:string)=>{const e=editorRef.current;if(!e)return;const shape=e.getCurrentPageShapes().find((s):s is PoiShape=>s.type===POI&&s.props.poiId===poiId);if(!shape)return;const visibility=shape.props.visibility==='visible'?'hidden':'visible';e.updateShape<PoiShape>({id:shape.id,type:POI,isLocked:false});e.updateShape<PoiShape>({id:shape.id,type:POI,isLocked:true,props:{visibility}});setPoiStates((current)=>({...current,[poiId]:visibility}));if(preview?.kind==='poi'&&preview.id===poiId){if(visibility==='visible')openScenePreview('poi',poiId);else projectionSpotlightRef.current=null}scheduleProjectionSync()}
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement||(target instanceof HTMLElement&&target.isContentEditable))return;const editor=editorRef.current;if(!editor)return;if(!selected)return;if(event.key.toLowerCase()==='f'&&(mode==='edit'||mode==='run')){event.preventDefault();event.stopPropagation();flipSelectedToken();return}if((event.key==='<'||event.key==='>')&&(mode==='edit'||mode==='run')){event.preventDefault();event.stopPropagation();scaleSelectedToken(event.key==='>'?TOKEN_SCALE_STEP:1/TOKEN_SCALE_STEP);return}if(event.key.toLowerCase()==='h')update({visibility:selected.props.visibility==='visible'?'hidden':'visible'});if(event.key.toLowerCase()==='l')update({locked:!selected.props.locked})};window.addEventListener('keydown',onKey,true);return()=>window.removeEventListener('keydown',onKey,true)})
 const previewEntity=preview?.kind==='entity'?entityMap.get(preview.id):undefined,previewPoi=preview?.kind==='poi'?poiMap.get(preview.id):undefined
return <ModeCtx.Provider value={mode}><PresentationPoisCtx.Provider value={presentationPoisVisible}><EntityCtx.Provider value={entityMap}><PoiCtx.Provider value={poiMap}><GridCtx.Provider value={grid}><div className={styles.shell} data-scene-mode={mode}><PageScrollLock/><div className={styles.canvas}><Tldraw shapeUtils={shapeUtils} overrides={sceneUiOverrides} snapshot={(scene.canvasSnapshot??undefined) as TLEditorSnapshot|undefined} onMount={onMount} options={{createTextOnCanvasDoubleClick:false}} colorScheme="dark" licenseKey={process.env.NEXT_PUBLIC_TLDRAW_LICENSE_KEY} components={{PageMenu:null,MainMenu:null,MenuPanel:null,QuickActions:null,Toolbar:null,StylePanel:null,NavigationPanel:null,ActionsMenu:null}}/></div>
 {mode!=='presentation'&&<><header className={styles.header}><Link href="/scenes"><ArrowLeft/></Link><Clapperboard/><div><small>{locationTitle}</small><strong>{scene.title}</strong></div><nav><button className={mode==='edit'?styles.active:''} onClick={()=>setMode('edit')}>Preparar</button><button className={mode==='run'?styles.active:''} onClick={()=>setMode('run')}>Mestrar</button><button onClick={()=>{setMode('presentation');const url=new URL(window.location.href);url.searchParams.set('mode','presentation');window.history.replaceState(null,'',url)}}><MonitorPlay/>Apresentar</button></nav><button className={styles.sceneSwitch} onClick={()=>setPickerOpen(true)} title="Trocar cena"><Clapperboard/><span>Trocar cena</span></button><span className={styles.saved}>{saved&&<Check/>}{saved?'Salvo':'Alterações...'}</span></header>
 <aside className={`${styles.scenePanel} ${!runPanelOpen?styles.scenePanelCollapsed:''}`}><h2>{mode==='edit'?'PREPARAR CENA':'MESTRAR CENA'}</h2>{mode==='edit'?<><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Adicionar token"/></label><div className={styles.entities}>{filtered.map(e=><button key={e.id} onClick={()=>addToken(e.id)}><EntityTypeIcon name={e.typeIcon}/><span>{e.title}<small>{e.typeLabel}</small></span><Plus/></button>)}</div><section><h3>Grade</h3><label><input type="checkbox" checked={grid.enabled} onChange={e=>changeGrid({enabled:e.target.checked})}/> Exibir grade</label><label><input type="checkbox" checked={grid.snapTokens} onChange={e=>changeGrid({snapTokens:e.target.checked})}/> Encaixar tokens redondos</label><label>Tamanho <input type="number" min="20" max="300" value={grid.cellSize} onChange={e=>changeGrid({cellSize:Number(e.target.value)})}/></label><label>Posição X <input type="number" value={grid.offsetX} onChange={e=>changeGrid({offsetX:Number(e.target.value)})}/></label><label>Posição Y <input type="number" value={grid.offsetY} onChange={e=>changeGrid({offsetY:Number(e.target.value)})}/></label><label>Opacidade <input type="range" min="0.05" max="0.8" step="0.05" value={grid.opacity} onChange={e=>changeGrid({opacity:Number(e.target.value)})}/></label></section></>:<section className={styles.runTokens}><h3>Tokens em cena</h3>{tokens.map((token)=><button key={token.id} onClick={()=>toggleToken(token)}>{token.props.visibility==='hidden'?<EyeOff/>:<Eye/>}<span>{entityMap.get(token.props.entityId)?.title??'Entidade ausente'}</span></button>)}</section>}<section><h3>Pontos de interesse</h3><div className={styles.rowActions}><button onClick={()=>allPois('visible')}><Eye/>Mostrar</button><button onClick={()=>allPois('hidden')}><EyeOff/>Ocultar</button></div><div className={styles.poiList}>{pois.map((p)=><button key={p.id} onClick={()=>togglePoi(p.id)}>{poiStates[p.id]==='hidden'?<EyeOff/>:<Eye/>}<span>{p.label}</span></button>)}</div></section></aside></>}
 {mode!=='presentation'&&<button className={`${styles.runPanelToggle} ${!runPanelOpen?styles.runPanelToggleCollapsed:''}`} onClick={()=>setRunPanelOpen((open)=>!open)} title={runPanelOpen?'Ocultar painel':'Mostrar painel'}>{runPanelOpen?<ChevronLeft/>:<ChevronRight/>}</button>}
 {mode!=='presentation'&&<aside className={`${styles.projectionPanel} ${!runPanelOpen?styles.projectionPanelExpanded:''}`}><div className={styles.projectionHeading}><span><Cast/>Projeção</span><strong className={projectionConnected?styles.connected:styles.disconnectedState}><i/>{projectionActive?(projectionConnected?'Conectada':'Aguardando'):'Inativa'}</strong></div><label><input type="checkbox" checked={followCamera} onChange={(event)=>{followCameraRef.current=event.target.checked;setFollowCamera(event.target.checked);scheduleProjectionSync()}}/> Acompanhar câmera do mestre</label><dl><div><dt>Tokens</dt><dd>{tokens.filter((token)=>token.props.visibility==='visible').length} visíveis · {tokens.filter((token)=>token.props.visibility==='hidden').length} ocultos</dd></div><div><dt>Pontos</dt><dd>{Object.values(poiStates).filter((value)=>value==='visible').length} revelados · {Object.values(poiStates).filter((value)=>value==='hidden').length} ocultos</dd></div></dl><div className={styles.projectionActions}><button onClick={startProjection}><Cast/>{projectionActive?'Exibir cena':'Projetar cena'}</button><button onClick={togglePlayerPreview}><Eye/>{playerPreview?'Fechar prévia':'Prévia do jogador'}</button>{projectionActive&&<button onClick={stopProjection}><Square/>Encerrar projeção</button>}</div></aside>}
 <div className={styles.camera}><button onClick={()=>editorRef.current?.zoomToBounds({x:0,y:0,w:scene.background.width,h:scene.background.height},{inset:40,animation:{duration:250}})} title="Enquadrar cena"><Focus/></button><button onClick={()=>document.documentElement.requestFullscreen()} title="Tela cheia"><Maximize/></button></div>
 {selected&&mode==='edit'&&<aside className={styles.inspector}><button className={styles.close} onClick={()=>editorRef.current?.selectNone()}><X/></button><small>Token</small><h2>{entityMap.get(selected.props.entityId)?.title??'Entidade ausente'}</h2><div className={styles.quick}><button onClick={()=>update({visibility:selected.props.visibility==='visible'?'hidden':'visible'})}>{selected.props.visibility==='visible'?<EyeOff/>:<Eye/>}{selected.props.visibility==='visible'?'Ocultar':'Revelar'}</button><button onClick={()=>{const round=selected.props.representation!=='round';update({representation:round?'round':'cutout',...(round?{w:140,h:140}:{w:180,h:280})})}}>Alternar visual</button><button onClick={flipSelectedToken}>Inverter horizontalmente</button><button onClick={()=>update({locked:!selected.props.locked})}>{selected.props.locked?<LockOpen/>:<Lock/>}{selected.props.locked?'Destravar':'Travar'}</button></div><div className={styles.zorder}><button onClick={()=>editorRef.current?.bringToFront([selected.id])}>Trazer à frente</button><button onClick={()=>{const editor=editorRef.current;if(!editor)return;editor.sendToBack([selected.id]);const background=editor.getCurrentPageShapes().find(s=>s.type===BG);if(background)editor.sendToBack([background.id])}}>Enviar para trás</button></div><Link href={`/entity/${selected.props.entityId}`}>Abrir entidade</Link><p className={styles.shortcutHint}><kbd>F</kbd> inverter <span>·</span> <kbd>&lt;</kbd> diminuir <span>·</span> <kbd>&gt;</kbd> aumentar</p></aside>}
 {mode==='run'&&preview&&<SceneQuickPanel entity={previewEntity} poi={previewPoi} onClose={closeScenePreview} onNavigate={(href)=>router.push(href)} revealable={Boolean(previewPoi)} revealedDiscoveryIds={previewPoi?revealedPoiInfo[previewPoi.id]??[]:[]} onToggleDiscovery={(id)=>previewPoi&&togglePoiDiscovery(previewPoi.id,id)}/>}
 {pickerOpen&&<ScenePicker scenes={scenes} currentId={scene.id} onPick={goToScene} onClose={()=>setPickerOpen(false)}/>}
 {playerPreview&&<div className={styles.playerPreview}><ProjectionDisplay state={playerState}/><header><span><Radio/>Prévia do jogador</span><button onClick={togglePlayerPreview}><X/></button></header></div>}
 {mode==='presentation'&&<><div className={styles.presentationBar}><button onClick={()=>{closeScenePreview();setMode('run');const url=new URL(window.location.href);url.searchParams.delete('mode');window.history.replaceState(null,'',url)}} title="Sair da apresentação"><ArrowLeft/><span>Sair da apresentação</span></button><button onClick={()=>setPresentationPoisVisible((visible)=>!visible)} title={presentationPoisVisible?'Ocultar pontos de interesse':'Mostrar pontos de interesse'}>{presentationPoisVisible?<EyeOff/>:<Eye/>}<span>{presentationPoisVisible?'Ocultar pontos':'Mostrar pontos'}</span></button><button onClick={()=>setPickerOpen(true)} title="Trocar cena"><Clapperboard/><span>Trocar cena</span></button></div>{preview&&<SceneQuickPanel entity={previewEntity} poi={previewPoi} onClose={closeScenePreview} onNavigate={(href)=>router.push(href)}/>}</>}</div></GridCtx.Provider></PoiCtx.Provider></EntityCtx.Provider></PresentationPoisCtx.Provider></ModeCtx.Provider>
}
